apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: metrics-server
    releaseName: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.12.1
    namespace: kube-system
    valuesFile: metrics-server-values.yaml
